/* Generated by tools/build-service-worker.mjs. */
const CACHE = "gridmind-0f87c9876f863598";
const ASSETS = [
  "./apple-touch-icon.png",
  "./assets/code-Dbemu-3K.js",
  "./assets/docs-D1B5eqL0.js",
  "./assets/editor-core-f0OZoZBI.js",
  "./assets/editor-css-kOAlm-08.js",
  "./assets/editor-html-D3nHRolU.js",
  "./assets/editor-javascript-DrrRwOp-.js",
  "./assets/editor-json-C5nHN4U2.js",
  "./assets/editor-python-DGrxLDNd.js",
  "./assets/index-2BB0_BoG.css",
  "./assets/index-XHCgTuqa.js",
  "./assets/lessons-CdiGwub3.js",
  "./assets/marked.esm-CqY386hz.js",
  "./code.json",
  "./docs.json",
  "./icon-192.png",
  "./icon-512.png",
  "./icon.svg",
  "./index.html",
  "./lessons.json",
  "./manifest.webmanifest",
  "./puzzles.json"
];

self.addEventListener("install", (event) => {
  event.waitUntil(caches.open(CACHE).then((cache) => cache.addAll(ASSETS)));
  self.skipWaiting();
});

self.addEventListener("activate", (event) => {
  event.waitUntil(
    caches.keys().then((keys) =>
      Promise.all(keys.filter((key) => key.startsWith("gridmind-") && key !== CACHE)
        .map((key) => caches.delete(key))),
    ),
  );
  self.clients.claim();
});

self.addEventListener("fetch", (event) => {
  if (event.request.method !== "GET") return;
  event.respondWith(
    caches.match(event.request).then((cached) => cached || fetch(event.request).then((response) => {
      if (response.ok && new URL(event.request.url).origin === self.location.origin) {
        const copy = response.clone();
        caches.open(CACHE).then((cache) => cache.put(event.request, copy));
      }
      return response;
    })),
  );
});
